ZSH becomes pre-requirements

diff --git a/dotfiles b/dotfiles
--- a/dotfiles
+++ b/dotfiles
@@ -174,6 +174,11 @@ function install_zsh() {
   sudo shutdown -r 0
 }
 
+if ! which zsh; then
+  printf '%s\n\n' 'dotfiles: zsh not found!' >&2
+  install_zsh
+fi
+
 ### Start main program ###
 if [ "$NO_GIT" == false ]; then
   configure_git
@@ -190,8 +195,4 @@ fi
 if [ "$NO_NODE" == false ]; then
   install_node
 fi
-
-
-# Finally, let's install ZSH
-install_zsh
 ### End main program ###
